version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile

    image: treino-django
    container_name: treino-django
    depends_on:
      - nginx
    env_file:
     - .env
    volumes:
     - static_volume:/app/static
     - media_volume:/app/media
     - banco_volume:/app/banco
    
    command: ./start
    restart: unless-stopped


  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    container_name: treino-nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 83:80
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  banco_volume:

