version : "3"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile

    image:  django_project
    depends_on:
      - nginx
    env_file:
      - .env
    volumes:
      - static_data:/app/static
      - banco_data:/app/banco
      - media_data:/app/media

    command: ./start
    restart: unless-stopped
  
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - static_data:/app/static
      - media_data:/app/media 
    ports:
      - 82:80
    restart: unless-stopped


volumes:
  banco_data:
  static_data:
  media_data: