# Generated by Django 5.1 on 2024-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ManyToManyField(to='suap.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.CharField(max_length=50),
        ),
    ]
