# Generated by Django 5.1 on 2024-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap', '0002_remove_curso_alunos_aluno_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
