# Generated by Django 5.1 on 2024-08-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap', '0004_remove_aluno_matricula_aluno_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='curso/'),
        ),
    ]
